mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views import home, discount, new_arrive, delivery_info, payment_info, return_info

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('discount/', discount, name='discount'),
    path('new-arrive/', new_arrive, name='new_arrive'),
    path('delivery/', delivery_info, name='delivery'),
    path('payment/', payment_info, name='payment'),
    path('return/', return_info, name='return'),
    path('profile/', include(('users.urls', 'accounts')))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import registration_view

app_name = 'accounts'

urlpatterns = [
    path('register/', registration_view, name='register'),
]

products/models.py
from django.db import models


class Category(models.Model):
    category = models.CharField(max_length=40)
    image = models.ImageField(verbose_name='Фото', upload_to='static/images/categories', null=True)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название товара', unique=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    price = models.IntegerField(verbose_name='Цена')
    description = models.CharField(max_length=150, null=True, blank=True, verbose_name='Описание')
    image = models.ImageField(verbose_name='Фото', upload_to='static/images/products', null=True)
    is_discount = models.BooleanField(verbose_name='Акция', null=True, blank=True)
    is_new = models.BooleanField(verbose_name='Новинка', null=True, blank=True)

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    phone = models.IntegerField()
    birth_date = models.DateField()

    def __str__(self):
        return self.user

users/forms.py
from django.db import models
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.hashers import check_password
from users.models import Profile


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите имя юзера'
    }))

    email = forms.CharField(label='Email', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите email'
    }))

    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Введите пароль'
    }))
    password2 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Подтвердите пароль'
    }))

    birth_date = forms.DateTimeField(label='Дата рождения', widget=forms.DateTimeInput(attrs={
        'class': 'form-control',
        'placeholder': 'Дата рождения'
    }))

    phone = forms.IntegerField(label='Номер телефона', widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Номер телефона'
    }))

    class Meta:
        model = Profile
        fields = ('phone', )

products/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render
from products.models import Product, Category


def home(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    return render(request, 'products/home.html', {'categories': categories, 'products': products})


def discount(request):
    discounts = Product.objects.filter(is_discount=True).all()
    return render(request, 'products/products_list.html', {'products': discounts})


def new_arrive(request):
    new_arrives = Product.objects.all()
    return render(request, 'products/products_list.html', {'products': new_arrives})


def delivery_info(request):
    return render(request, 'products/delivery_info.html')


def payment_info(request):
    return render(request, 'products/payment_info.html')


def return_info(request):
    return render(request, 'products/return_info.html')

users/views.py
from django.shortcuts import render
from users.forms import UserRegistrationForm


def registration_view(request):
    form = UserRegistrationForm(request.POST)
    return render(request, 'users/registration.html', {'form': form})

products/templates/products/delivery_info.html
{% extends 'base/base.html' %}
{% block title%}Главная{% endblock %}
{% block content %}

<div class="bg-light">
  <div class="container">
    <br>
    <h3>Доставка</h3>
    <br>
    <div class="row">

      <div class="containe bg-white">
        <div class="container">
          <br>
          <p>Доставка товаров в наличии осуществляется по следующей схеме:</p>

          <p>После подтверждения Вами заказа, мы упаковавывам его и в течение 2-х дней отправляем:</p>

          <p>- Курьером (только для жителей г. Ангарска).</p>
          <p>Стоимость доставки - 100 руб.</p>

          <p>- Почтой России (для жителей других регионов РФ).</p>
          <p>Срок доставки по России - от нескольких дней до 2-х недель.</p>
          <p>Стоимость доставки рассчитывается автоматически при оформлении заказа, исходя из веса и стоимости товаров (для расчетов используется сервис http://postcalc.ru).</p>



          <p>Доставка товаров под заказ осуществляется по следующей схеме:</p>

          <p>1. Раз в неделю мы отправляем заявку со всеми подтвержденными заказами (за неделю) нашим поставщикам.</p>
          <p>2. К сожалению иногда случается так, что некоторых товаров (размеров) может не оказаться у поставщиков, поэтому в течение нескольких дней они отправляют нам нашу заявку с пометками, если каких-то товаров у них не оказалось. Если в числе
            отсутствующих оказывается какой-либо товар из Вашего заказа, мы сообщаем Вам об этом по e-mail. Если Вы получили такое письмо от нас, то Вы можете отказаться от отсутствующей вещи либо заменить ее на другую.</p>

          <p>3. Поставщики высылают заказанные товары нам (в г.Ангарск).</p>

          <p>4. Мы получаем товар, отправляем Вам e-mail и смс с просьбой подтвердить отправку (либо с реквизитами для оплаты, если Вы выбрали предоплату), и в случае положительного ответа (либо поступления оплаты) высылаем его Вам. После отправки к
            Вам на e-mail и по смс придет идентификатор посылки.</p>

          <p>Примерный срок доставки товара до нас - 6 недель с момента оформления Вами заказа.</p>

          <p>Примерный срок доставки заказа до Вас - 7 недель с момента оформления Вами заказа (или 1 неделю после прихода заказа к нам).</p>

          <p>Если Ваш заказ содержит как товары в наличии, так и товары под заказ, то по умолчанию отправка всего Вашего заказа произойдет только после получения нами товаров на заказ. Если вы хотите получить товары в наличии раньше, то разбивайте
            товары на 2 заказа: в один включайте только товары в наличии, в другой - только товары под заказ.</p>

          <p>ВНИМАНИЕ! Посылки хранятся в отделениях почты 30 дней с момента их поступления, после этого их отправляют обратно. Если у Вас нет финансовой возможности (при оплате заказа на почте) забрать посылку в течение 30 дней, то срок хранения
            можно продлить до 2-х месяцев. Для этого необходимо с паспортом обратиться в Ваше почтовое отделение.</p>
        </div>
      </div>
    </div>
    <br>
  </div>
</div>

{%endblock%}

products/templates/products/home.html
{% extends 'base/base.html' %}
{% block title%}Главная{% endblock %}
{% block content %}
<div class="container">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    {% for item in categories %}
      {% if forloop.first %}
    <div class="carousel-item active">
      <img src="{{item.image}}" class="d-block w-100" alt="...">
    </div>
    {% else %}
    <div class="carousel-item">
      <img src="{{item.image}}" class="d-block w-100" alt="...">
    </div>
    {% endif %}
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
<br><br>
<div class="container mx-auto mt-4">
  <div class="row">
    {% for product in products|slice:":6" %}
    <div class="col-md-4 mb-5">
      <div class="card" style="width: 18rem;">
  <img class="rounded" src="{{product.image.url}}" class="card-img-top" alt="..."  width="200"
     height="200">
  <div class="card-body">
    <h5 class="card-title">{{product.name}}</h5>
        <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
       <a href="#" class="link-secondary">{{product.price}}</a>
    <a href="#" class="link-secondary"><i class="fab fa-github"></i></a>
  </div>
  </div>
    </div>
{% endfor %}
</div>
  </div>
{%endblock%}

products/templates/products/payment_info.html
{% extends 'base/base.html' %}
{% block title%}Главная{% endblock %}
{% block content %}

<div class="bg-light">
  <div class="container">
    <br>
    <h3>Оплата</h3>
    <br>
    <div class="row">

      <div class="containe bg-white">
        <div class="container">
          <p>Возможны следующие варианты оплаты:</p>

          <p>1. Предоплата</p>

          <p>После оформления Вами заказа (для товаров в наличии) либо после того, как мы получаем от поставщиков Ваш заказ (для товаров под заказ), мы сообщаем Вам реквизиты для оплаты. После совершения Вами оплаты, мы высылаем Вам Ваш заказ в
            течение 2-х дней. При получении ничего платить не нужно. При данном варианте оплаты, в отличие от оплаты при получении, дешевле обходится доставка, плюс Вам не придется платить комиссию за перевод на почте.</p>
          <p>Предоплата может осуществляться следующими способами:</p>
          <p>1.1. Через Сбербанк (необходима карточка Сберабанка). Вы идете к ближайшему банкомату и осуществляете перевод средств с Вашей карты на нашу карту (номер мы сообщим по e-mail). Если на Вашей карте нет денег, но они есть в виде наличных,
            то Вы сначала кладете деньги на Вашу карту, а потом осуществляете перевод. Также можно произвести перевод через Сбербанк-онлайн либо мобильный банк. После того, как сделаете перевод, напишите нам об этом (при оплате через Сбербанк Онлайн
            можете указать в</p>
          <p>комментарии свою фамилию, но не нужно указывать слово "заказ"). Комиссия за перевод 1%.</p>

          <p>1.2. По карте любого банка. Мы сообщаем Вам номер нашей карты Тинькофф, вы осуществляете перевод по данной ссылке: https://www.tinkoff.ru/cardtocard/ (номер нашей карты указывается справа). После того, как сделаете перевод, напишите нам
            об этом. Комиссия за перевод зависит от Вашего банка, но в большинстве случаев перевод осуществляется без комиссии.</p>

          <p>1.3. Через Qiwi-терминал. Вы идете к ближайшему Qiwi-терминалу и вносите деньги на наш Qiwi-кошелек (номер мы сообщим по e-mail). В комментарии к платежу обязательно указываете номер оплачиваемого заказа или Ваши ФИО, чтобы мы могли
            идентифицировать Ваш платеж. В случае использования именно Qiwi-терминала внесение осуществляется без комиссии.</p>

          <p>1.4. Через Яндекс-деньги. Мы сообщаем по e-mail наш счет в Яндекс-деньгах, Вы переводите деньги с Вашего счета на наш. В комментарии к платежу указываете номер оплачиваемого заказа или Ваши ФИО, чтобы мы могли идентифицировать Ваш
            платеж. Комиссия за перевод 0,5%</p>

          <p>1.5. Через WebMoney. Мы сообщаем по e-mail наш счет в WebMoney, Вы переводите деньги с Вашего счета на наш. В комментарии к платежу указываете номер оплачиваемого заказа или Ваши ФИО, чтобы мы могли идентифицировать Ваш платеж. Комиссия
            за перевод 0,8%</p>


          <p>2. Оплата при получении</p>

          <p>Вы оплачиваете покупку на почте при получении заказа (наложенный платеж).</p>
          <p>При данном варианте оплаты, в отличии от предоплаты, дороже обходится доставка, плюс за перевод денег почта берет некоторый процент, ознакомиться с которым можно по ссылке: тарифы почты России. Кроме того, для некоторых регионов
            дополнительно к базовому взимается индивидуальный тариф, который можно посмотреть здесь: дополнительный тариф</p>


          <p>Для жителей г.Ангарска оплата производится наличными курьеру при получении.</p>
        </div>
      </div>
    </div>
    <br>
  </div>
</div>

{%endblock%}

products/templates/products/products_list.html
{% extends 'base/base.html' %}
{% block title%}Главная{% endblock %}
{% block content %}
<div class="container mx-auto mt-4">
  <div class="row">
    {% for product in products %}
    <div class="col-md-4 mb-5">
      <div class="card" style="width: 18rem;">
        <img src="{{ product.image.url }}" alt="..."  width="200"
           height="200">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
          <a href="#" class="link-secondary">{{product.price}}</a>
          <a href="#" class="link-secondary"><i class="fab fa-github"></i> {{product.image}}</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{%endblock%}

products/templates/products/return_info.html
{% extends 'base/base.html' %}
{% block title%}Главная{% endblock %}
{% block content %}

<div class="bg-light">
  <div class="container">
    <br>
    <h3>Возврат</h3>
    <br>
    <div class="row">

      <div class="containe bg-white">
        <div class="container">
          <br>
          <p>Возврат товаров возможен в течении 14 дней с момента получения Вами заказа. </p>

          <p>Если причиной возврата является брак, то мы возмещаем как стоимость самого товара, так и стоимость доставки (туда и обратно).</p>
          <p>При всех остальных причинах возврата мы возмещаем Вам только стоимость самого товара, доставка товара (туда и обратно) происходит за Ваш счет. Обязательное условие возврата - товары не должны быть использованы (т.е. не должны быть одеты
            на улицу или на тренировку).</p>

          <p>Для уведомления нас о Вашем желании вернуть товар напишите нам с помощью формы обратной связи или на адрес order@jordan23.su, в письме укажите номер заказа, товар и причину возврата. После этого мы свяжемся с Вами для дальнейших
            указаний.</p>
        </div>
      </div>
    </div>
    <br>
  </div>
</div>

{%endblock%}

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>{% block title %} {%endblock%}</title>
</head>

<body >
  <nav class='header-nav'>
    <div class="container text-secondary">
      <div class="row">
        <div class="col-md-5 hidden-sm-down">
          <a href="{% url 'home' %}"><img src="{% static 'logo/shop_logo.png' %}" alt="Shop logo" width="240" height="100"></a>
        </div>
        <div class="col-md-7 right-nav">
          <div class="row py-3">
            <div class="col pt-4">
              <a href="#" class="link-secondary">Написать нам</a>
            </div>
            <div class="col pt-4">
              <div class="row">
              <div class="col">
              <a href="#" class="link-secondary">Вход</a>
            </div>
              <div class="col">
              <a href="{% url 'accounts:register' %}" class="link-secondary">Регистрация</a>
            </div>
            </div>
            </div>
            <div class="col pt-4">
              <a href="#" class="link-secondary">Корзина</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </nav>
  <hr>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 position-static">
        <div class="row">
          <div class="col-lg-8 col-md-6 js-top-menu position-static hidden-sm-down">
            <div class="row">
              <li class="col link-secondary">Товары в наличии</li>
              <li class="col link-secondary">Товары под заказ</li>
            </div>
            <div class="row">
              <li class="col link-secondary"><a class="link-secondary" href="#">Распродажа</a></li>
              <li class="col link-secondary"><a class="link-secondary" href="#">Отзывы</a></li>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 js-top-menu position-static hidden-sm-down">
            <div class="input-group">
              <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
              <button type="button" class="btn btn-secondary">search</button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr style='padding-bottom: 0px; margin-bottom: 0px;'>
  {% block content%}
  {% endblock %}
  <hr style='padding-top: 0px; margin-top: 0px;'>
  <div class="footer-container">
    <div class="container">
      <div class="row">
        <div class="col-md-6 links">
          <div class="row">
            <div class="col-md-6 wrapper">
              <h5 class='h5 hidden-sm-down'>Акции</h5>
              <a href="{% url 'discount' %}" class="link-secondary">Снижение цен</a>
              <br>
              <a href="{% url 'new_arrive' %}" class="link-secondary">Новинки</a>
            </div>
            <div class="col-md-6 links">
              <div class="row">
                <div class="col-md-6 wrapper">
                  <h5 class='h5 hidden-sm-down'>Информация</h5>
                  <a href="{% url 'delivery' %}" class="link-secondary">Доставка</a>
                  <br>
                  <a href="{% url 'payment' %}" class="link-secondary">Оплата</a>
                  <br>
                  <a href="#" class="link-secondary">Обратная связь</a>
                  <br>
                  <a href="{% url 'return' %}" class="link-secondary">Возврат</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3 links wrapper">
          <h5 class='h5 hidden-sm-down'>Личный кабинет</h5>
          <a href="#" class="link-secondary">Личные данные</a>
          <br>
          <a href="#" class="link-secondary">Адреса</a>
          <br>
          <a href="#" class="link-secondary">Заказы</a>
        </div>
        <div class="col-md-3 links wrapper">
          <h5 class='h5 hidden-sm-down'>Контакты</h5>
          <p class="link-secondary">Россия
            г.Ангарск, Иркутская обл.
            Email: order@jordan23.su</p>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>

</html>

templates/base/form.html
<div class="container">
<div class="row justify-content-md-center">
  <div class="col-md-6">
    <form action = "{{action}}" method='post' enctype="multipart/form-data"> {% csrf_token %}
            {{form.as_p}}
        <button type="submit" class="btn btn-primary">{{button}}</button>
    </form>
  </div>
</div>
</div>

users/templates/users/register_done.html
{% extends 'base.html' %}
{% block title %}Форма регистрации{% endblock %}

{% block content %}
<div class="container">
  <div class="row p-5">
<h1>Добро пожаловать:)</h1>
<p>Вы зарегистрировались в системе. Теперь вы можете <a href="{% url 'accounts:login' %}">войти</a></p>
</div>
</div>


{% endblock %}

users/templates/users/registration.html
{% extends 'base/base.html' %}
{% block title%}Главная{% endblock %}
{% block content %}
<div class="bg-light">
  <div class="container">
    <br>
    <h3>Регистрация</h3>
    <br>
    <div class="row">

      <div class="container bg-white col-6">
        <div class="container p-4">
          <!-- <div class="col-6"> -->
            {% include 'base/form.html' with button='Зарегистрироваться'%}
          <!-- </div> -->
        </div>
      </div>
    </div>
    <br>
  </div>
</div>

{%endblock%}